// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="a3_via_dma_in1,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z045-ffg900-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=625,HLS_SYN_LUT=665,HLS_VERSION=2019_1}" *)

module a3_via_dma_in1 (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_in1_AWVALID,
        m_axi_in1_AWREADY,
        m_axi_in1_AWADDR,
        m_axi_in1_AWID,
        m_axi_in1_AWLEN,
        m_axi_in1_AWSIZE,
        m_axi_in1_AWBURST,
        m_axi_in1_AWLOCK,
        m_axi_in1_AWCACHE,
        m_axi_in1_AWPROT,
        m_axi_in1_AWQOS,
        m_axi_in1_AWREGION,
        m_axi_in1_AWUSER,
        m_axi_in1_WVALID,
        m_axi_in1_WREADY,
        m_axi_in1_WDATA,
        m_axi_in1_WSTRB,
        m_axi_in1_WLAST,
        m_axi_in1_WID,
        m_axi_in1_WUSER,
        m_axi_in1_ARVALID,
        m_axi_in1_ARREADY,
        m_axi_in1_ARADDR,
        m_axi_in1_ARID,
        m_axi_in1_ARLEN,
        m_axi_in1_ARSIZE,
        m_axi_in1_ARBURST,
        m_axi_in1_ARLOCK,
        m_axi_in1_ARCACHE,
        m_axi_in1_ARPROT,
        m_axi_in1_ARQOS,
        m_axi_in1_ARREGION,
        m_axi_in1_ARUSER,
        m_axi_in1_RVALID,
        m_axi_in1_RREADY,
        m_axi_in1_RDATA,
        m_axi_in1_RLAST,
        m_axi_in1_RID,
        m_axi_in1_RUSER,
        m_axi_in1_RRESP,
        m_axi_in1_BVALID,
        m_axi_in1_BREADY,
        m_axi_in1_BRESP,
        m_axi_in1_BID,
        m_axi_in1_BUSER,
        in1_offset,
        len,
        weight_TDATA,
        weight_TVALID,
        weight_TREADY
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_pp0_stage0 = 9'd128;
parameter    ap_ST_fsm_state11 = 9'd256;
parameter    C_M_AXI_IN1_ID_WIDTH = 1;
parameter    C_M_AXI_IN1_ADDR_WIDTH = 32;
parameter    C_M_AXI_IN1_DATA_WIDTH = 32;
parameter    C_M_AXI_IN1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_IN1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_IN1_WUSER_WIDTH = 1;
parameter    C_M_AXI_IN1_RUSER_WIDTH = 1;
parameter    C_M_AXI_IN1_BUSER_WIDTH = 1;
parameter    C_M_AXI_IN1_USER_VALUE = 0;
parameter    C_M_AXI_IN1_PROT_VALUE = 0;
parameter    C_M_AXI_IN1_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_M_AXI_IN1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_in1_AWVALID;
input   m_axi_in1_AWREADY;
output  [C_M_AXI_IN1_ADDR_WIDTH - 1:0] m_axi_in1_AWADDR;
output  [C_M_AXI_IN1_ID_WIDTH - 1:0] m_axi_in1_AWID;
output  [7:0] m_axi_in1_AWLEN;
output  [2:0] m_axi_in1_AWSIZE;
output  [1:0] m_axi_in1_AWBURST;
output  [1:0] m_axi_in1_AWLOCK;
output  [3:0] m_axi_in1_AWCACHE;
output  [2:0] m_axi_in1_AWPROT;
output  [3:0] m_axi_in1_AWQOS;
output  [3:0] m_axi_in1_AWREGION;
output  [C_M_AXI_IN1_AWUSER_WIDTH - 1:0] m_axi_in1_AWUSER;
output   m_axi_in1_WVALID;
input   m_axi_in1_WREADY;
output  [C_M_AXI_IN1_DATA_WIDTH - 1:0] m_axi_in1_WDATA;
output  [C_M_AXI_IN1_WSTRB_WIDTH - 1:0] m_axi_in1_WSTRB;
output   m_axi_in1_WLAST;
output  [C_M_AXI_IN1_ID_WIDTH - 1:0] m_axi_in1_WID;
output  [C_M_AXI_IN1_WUSER_WIDTH - 1:0] m_axi_in1_WUSER;
output   m_axi_in1_ARVALID;
input   m_axi_in1_ARREADY;
output  [C_M_AXI_IN1_ADDR_WIDTH - 1:0] m_axi_in1_ARADDR;
output  [C_M_AXI_IN1_ID_WIDTH - 1:0] m_axi_in1_ARID;
output  [7:0] m_axi_in1_ARLEN;
output  [2:0] m_axi_in1_ARSIZE;
output  [1:0] m_axi_in1_ARBURST;
output  [1:0] m_axi_in1_ARLOCK;
output  [3:0] m_axi_in1_ARCACHE;
output  [2:0] m_axi_in1_ARPROT;
output  [3:0] m_axi_in1_ARQOS;
output  [3:0] m_axi_in1_ARREGION;
output  [C_M_AXI_IN1_ARUSER_WIDTH - 1:0] m_axi_in1_ARUSER;
input   m_axi_in1_RVALID;
output   m_axi_in1_RREADY;
input  [C_M_AXI_IN1_DATA_WIDTH - 1:0] m_axi_in1_RDATA;
input   m_axi_in1_RLAST;
input  [C_M_AXI_IN1_ID_WIDTH - 1:0] m_axi_in1_RID;
input  [C_M_AXI_IN1_RUSER_WIDTH - 1:0] m_axi_in1_RUSER;
input  [1:0] m_axi_in1_RRESP;
input   m_axi_in1_BVALID;
output   m_axi_in1_BREADY;
input  [1:0] m_axi_in1_BRESP;
input  [C_M_AXI_IN1_ID_WIDTH - 1:0] m_axi_in1_BID;
input  [C_M_AXI_IN1_BUSER_WIDTH - 1:0] m_axi_in1_BUSER;
input  [31:0] in1_offset;
input  [31:0] len;
output  [31:0] weight_TDATA;
output   weight_TVALID;
input   weight_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] weight_1_data_out;
reg    weight_1_vld_in;
wire    weight_1_vld_out;
wire    weight_1_ack_in;
wire    weight_1_ack_out;
reg   [31:0] weight_1_payload_A;
reg   [31:0] weight_1_payload_B;
reg    weight_1_sel_rd;
reg    weight_1_sel_wr;
wire    weight_1_sel;
wire    weight_1_load_A;
wire    weight_1_load_B;
reg   [1:0] weight_1_state;
wire    weight_1_state_cmp_full;
reg    in1_blk_n_AR;
reg    in1_blk_n_R;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln28_reg_157;
reg    weight_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln28_reg_157_pp0_iter1_reg;
wire    in1_AWREADY;
wire    in1_WREADY;
reg    in1_ARVALID;
wire    in1_ARREADY;
wire    in1_RVALID;
reg    in1_RREADY;
wire   [31:0] in1_RDATA;
wire    in1_RLAST;
wire   [0:0] in1_RID;
wire   [0:0] in1_RUSER;
wire   [1:0] in1_RRESP;
wire    in1_BVALID;
wire   [1:0] in1_BRESP;
wire   [0:0] in1_BID;
wire   [0:0] in1_BUSER;
reg   [30:0] i_0_reg_98;
wire   [0:0] icmp_ln28_fu_134_p2;
wire    ap_block_state8_pp0_stage0_iter0;
reg    ap_block_state9_pp0_stage0_iter1;
reg    ap_block_state9_io;
wire    ap_block_state10_pp0_stage0_iter2;
reg    ap_block_state10_io;
reg    ap_block_pp0_stage0_11001;
wire   [30:0] i_fu_139_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_CS_fsm_state7;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state8;
wire   [31:0] empty_fu_119_p1;
reg    ap_block_pp0_stage0_01001;
wire   [29:0] in1_offset1_fu_109_p4;
wire   [31:0] zext_ln28_fu_130_p1;
wire    ap_CS_fsm_state11;
reg    ap_block_state11;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 weight_1_sel_rd = 1'b0;
#0 weight_1_sel_wr = 1'b0;
#0 weight_1_state = 2'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

a3_via_dma_in1_in1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_IN1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_IN1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_IN1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_IN1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_IN1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_IN1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_IN1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_IN1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_IN1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_IN1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_IN1_CACHE_VALUE ))
via_dma_in1_in1_m_axi_U(
    .AWVALID(m_axi_in1_AWVALID),
    .AWREADY(m_axi_in1_AWREADY),
    .AWADDR(m_axi_in1_AWADDR),
    .AWID(m_axi_in1_AWID),
    .AWLEN(m_axi_in1_AWLEN),
    .AWSIZE(m_axi_in1_AWSIZE),
    .AWBURST(m_axi_in1_AWBURST),
    .AWLOCK(m_axi_in1_AWLOCK),
    .AWCACHE(m_axi_in1_AWCACHE),
    .AWPROT(m_axi_in1_AWPROT),
    .AWQOS(m_axi_in1_AWQOS),
    .AWREGION(m_axi_in1_AWREGION),
    .AWUSER(m_axi_in1_AWUSER),
    .WVALID(m_axi_in1_WVALID),
    .WREADY(m_axi_in1_WREADY),
    .WDATA(m_axi_in1_WDATA),
    .WSTRB(m_axi_in1_WSTRB),
    .WLAST(m_axi_in1_WLAST),
    .WID(m_axi_in1_WID),
    .WUSER(m_axi_in1_WUSER),
    .ARVALID(m_axi_in1_ARVALID),
    .ARREADY(m_axi_in1_ARREADY),
    .ARADDR(m_axi_in1_ARADDR),
    .ARID(m_axi_in1_ARID),
    .ARLEN(m_axi_in1_ARLEN),
    .ARSIZE(m_axi_in1_ARSIZE),
    .ARBURST(m_axi_in1_ARBURST),
    .ARLOCK(m_axi_in1_ARLOCK),
    .ARCACHE(m_axi_in1_ARCACHE),
    .ARPROT(m_axi_in1_ARPROT),
    .ARQOS(m_axi_in1_ARQOS),
    .ARREGION(m_axi_in1_ARREGION),
    .ARUSER(m_axi_in1_ARUSER),
    .RVALID(m_axi_in1_RVALID),
    .RREADY(m_axi_in1_RREADY),
    .RDATA(m_axi_in1_RDATA),
    .RLAST(m_axi_in1_RLAST),
    .RID(m_axi_in1_RID),
    .RUSER(m_axi_in1_RUSER),
    .RRESP(m_axi_in1_RRESP),
    .BVALID(m_axi_in1_BVALID),
    .BREADY(m_axi_in1_BREADY),
    .BRESP(m_axi_in1_BRESP),
    .BID(m_axi_in1_BID),
    .BUSER(m_axi_in1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(in1_ARVALID),
    .I_ARREADY(in1_ARREADY),
    .I_ARADDR(empty_fu_119_p1),
    .I_ARID(1'd0),
    .I_ARLEN(len),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(in1_RVALID),
    .I_RREADY(in1_RREADY),
    .I_RDATA(in1_RDATA),
    .I_RID(in1_RID),
    .I_RUSER(in1_RUSER),
    .I_RRESP(in1_RRESP),
    .I_RLAST(in1_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(in1_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(in1_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(in1_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(in1_BRESP),
    .I_BID(in1_BID),
    .I_BUSER(in1_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state8) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state8)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state8);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        weight_1_sel_rd <= 1'b0;
    end else begin
        if (((weight_1_ack_out == 1'b1) & (weight_1_vld_out == 1'b1))) begin
            weight_1_sel_rd <= ~weight_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        weight_1_sel_wr <= 1'b0;
    end else begin
        if (((weight_1_ack_in == 1'b1) & (weight_1_vld_in == 1'b1))) begin
            weight_1_sel_wr <= ~weight_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        weight_1_state <= 2'd0;
    end else begin
        if ((((weight_1_vld_in == 1'b0) & (weight_1_state == 2'd2)) | ((weight_1_vld_in == 1'b0) & (weight_1_ack_out == 1'b1) & (weight_1_state == 2'd3)))) begin
            weight_1_state <= 2'd2;
        end else if ((((weight_TREADY == 1'b0) & (weight_1_state == 2'd1)) | ((weight_TREADY == 1'b0) & (weight_1_vld_in == 1'b1) & (weight_1_state == 2'd3)))) begin
            weight_1_state <= 2'd1;
        end else if (((~((weight_1_vld_in == 1'b0) & (weight_1_ack_out == 1'b1)) & ~((weight_TREADY == 1'b0) & (weight_1_vld_in == 1'b1)) & (weight_1_state == 2'd3)) | ((weight_1_ack_out == 1'b1) & (weight_1_state == 2'd1)) | ((weight_1_vld_in == 1'b1) & (weight_1_state == 2'd2)))) begin
            weight_1_state <= 2'd3;
        end else begin
            weight_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln28_fu_134_p2 == 1'd1))) begin
        i_0_reg_98 <= i_fu_139_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i_0_reg_98 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln28_reg_157 <= icmp_ln28_fu_134_p2;
        icmp_ln28_reg_157_pp0_iter1_reg <= icmp_ln28_reg_157;
    end
end

always @ (posedge ap_clk) begin
    if ((weight_1_load_A == 1'b1)) begin
        weight_1_payload_A <= in1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((weight_1_load_B == 1'b1)) begin
        weight_1_payload_B <= in1_RDATA;
    end
end

always @ (*) begin
    if ((icmp_ln28_fu_134_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if ((~((weight_1_state == 2'd1) | ((weight_TREADY == 1'b0) & (weight_1_state == 2'd3))) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((weight_1_state == 2'd1) | ((weight_TREADY == 1'b0) & (weight_1_state == 2'd3))) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((in1_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        in1_ARVALID = 1'b1;
    end else begin
        in1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln28_reg_157 == 1'd1))) begin
        in1_RREADY = 1'b1;
    end else begin
        in1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        in1_blk_n_AR = m_axi_in1_ARREADY;
    end else begin
        in1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln28_reg_157 == 1'd1))) begin
        in1_blk_n_R = m_axi_in1_RVALID;
    end else begin
        in1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((weight_1_sel == 1'b1)) begin
        weight_1_data_out = weight_1_payload_B;
    end else begin
        weight_1_data_out = weight_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln28_reg_157 == 1'd1))) begin
        weight_1_vld_in = 1'b1;
    end else begin
        weight_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln28_reg_157_pp0_iter1_reg == 1'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln28_reg_157 == 1'd1)))) begin
        weight_TDATA_blk_n = weight_1_state[1'd1];
    end else begin
        weight_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((in1_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln28_fu_134_p2 == 1'd0)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln28_fu_134_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~((weight_1_state == 2'd1) | ((weight_TREADY == 1'b0) & (weight_1_state == 2'd3))) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((in1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln28_reg_157 == 1'd1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state10_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state9_io) | ((in1_RVALID == 1'b0) & (icmp_ln28_reg_157 == 1'd1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state10_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state9_io) | ((in1_RVALID == 1'b0) & (icmp_ln28_reg_157 == 1'd1)))));
end

always @ (*) begin
    ap_block_state10_io = ((weight_1_ack_in == 1'b0) & (icmp_ln28_reg_157_pp0_iter1_reg == 1'd1));
end

assign ap_block_state10_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11 = ((weight_1_state == 2'd1) | ((weight_TREADY == 1'b0) & (weight_1_state == 2'd3)));
end

assign ap_block_state8_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_io = ((weight_1_ack_in == 1'b0) & (icmp_ln28_reg_157 == 1'd1));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1 = ((in1_RVALID == 1'b0) & (icmp_ln28_reg_157 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_fu_119_p1 = in1_offset1_fu_109_p4;

assign i_fu_139_p2 = (i_0_reg_98 + 31'd1);

assign icmp_ln28_fu_134_p2 = (($signed(zext_ln28_fu_130_p1) < $signed(len)) ? 1'b1 : 1'b0);

assign in1_offset1_fu_109_p4 = {{in1_offset[31:2]}};

assign weight_1_ack_in = weight_1_state[1'd1];

assign weight_1_ack_out = weight_TREADY;

assign weight_1_load_A = (weight_1_state_cmp_full & ~weight_1_sel_wr);

assign weight_1_load_B = (weight_1_state_cmp_full & weight_1_sel_wr);

assign weight_1_sel = weight_1_sel_rd;

assign weight_1_state_cmp_full = ((weight_1_state != 2'd1) ? 1'b1 : 1'b0);

assign weight_1_vld_out = weight_1_state[1'd0];

assign weight_TDATA = weight_1_data_out;

assign weight_TVALID = weight_1_state[1'd0];

assign zext_ln28_fu_130_p1 = i_0_reg_98;

endmodule //a3_via_dma_in1
